const Menu = [{
        id: 1,
        image: "images/dairy-milk.webp",
        name : "Dairy Milk",
        category : "Chocolate",
        price : 100,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur ",
    },
    {
        id: 2,
        image: "images/kit-kat.png",
        name : "Kit Kat",
        category : "Chocolate",
        price : 40,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur ",
    },
    {
        id: 3,
        image: "images/dark.png",
        name : "Dark Choco ",
        category : "Chocolate",
        price : 100,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur ",
    },
    {
        id: 4,
        image: "images/red-velvet.jpg",
        name : "Red Velevet Supreme",
        category : "Cup Cakes",
        price : 50,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur ",
    },
    {
        id: 5,
        image: "images/nutella.jpg",
        name : "Nutella brownie",
        category : "Cup Cakes",
        price : 60,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur ",
    },
    {
        id: 6,
        image: "images/chocolate.webp",
        name : "Double Chocolate",
        category : "Cup Cakes",
        price : 100,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur ",
    },
    {
        id: 7,
        image: "images/truffle.jpg",
        name : "Choco Truffle",
        category : "Cakes",
        price : 400,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur ",
    },
    {
        id: 8,
        image: "images/cheesecake.webp",
        name : "Nutella Chessecake",
        category : "Cakes",
        price : 700,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur ",
    },
    {
        id: 9,
        image: "images/pineapple-cake.jpeg",
        name : "Pineapple fun",
        category : "Cakes",
        price : 500,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur lore ",
    },
    {
        id: 10,
        image: "images/pineapple-cake.jpeg",
        name : "Cafe Latte",
        category : "Coffee",
        price : 200,
        description : "loreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consecteturloreorem ipsum dolor sit, amet consectetur lore ",
    },
];

export default Menu;